[package]
name = "connect4"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.11"        # Bevy for game engine and rendering
sdl2 = "0.35"        # SDL2 if you plan to use SDL2 directly (optional if you only use Bevy)
